### ISSUE TITLE
sorry i am noob , i get this error

### ISSUE THREAD

**Issue by gamarorit** [Pelipoika/TF2_NextBot#3]
Exception reported: Failed to create Call for CBaseAnimating::GetAttachment
L 09/05/2021 - 15:10:10: [SM] Blaming: tfpets.smx
L 09/05/2021 - 15:10:10: [SM] Call stack trace:
L 09/05/2021 - 15:10:10: [SM]   [0] SetFailState
L 09/05/2021 - 15:10:10: [SM]   [1] Line 2381, G:\server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\tfpets.sp::OnPluginStart

**Comment by Pelipoika** [comment]
Make sure your gamedata file is up to date
